src/Entity/Article.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\HttpFoundation\File\File;
use Vich\UploaderBundle\Mapping\Annotation as Vich;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;

/**
 * @ORM\Entity(repositoryClass="App\Repository\ArticleRepository")
 * @UniqueEntity("title")
 * @Vich\Uploadable
 */
class Article
{
    const CATEGORY = [
        0 => 'École',
        1 => 'Maternelle',
        2 => 'Élementaire',
        3 => 'Enseignement',
        4 => 'Restauration', 
        5 => 'Vacances',
        6 => 'Administratif'
    ];

    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @Assert\Length(min=3, max=255)
     * @ORM\Column(type="string", length=255)
     */
    private $title;

    /**
     * @ORM\Column(type="text")
     */
    private $content;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $category;

    /**
     * @ORM\Column(type="datetime")
     */
    private $created_at;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Classroom", cascade={"persist", "remove"}, inversedBy="articles")
     * @ORM\JoinColumn(onDelete="CASCADE")
     */
    private $classroom;

    /**
     * NOTE: This is not a mapped field of entity metadata, just a simple property.
     * 
     * @Vich\UploadableField(mapping="article_image", fileNameProperty="imageName")
     * @Assert\Image(mimeTypes="image/*")
     * @var File|null
     */
    private $imageFile;

    /**
     * @ORM\Column(type="string", nullable=true)
     *
     * @var string|null
     */
    private $imageName;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     *
     * @var \DateTimeInterface|null
     */
    private $updatedAt;

    public function __construct()
    {
        $this->created_at = new \DateTime();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(string $content): self
    {
        $this->content = $content;

        return $this;
    }

    public function getCategory(): ?string
    {
        return $this->category;
    }

    public function getCategoryType(): string
    {
        return self::CATEGORY[$this->category];
    }

    public function setCategory(?string $category): self
    {
        $this->category = $category;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getClassroom(): ?classroom
    {
        return $this->classroom;
    }

    public function setClassroom(?classroom $classroom): self
    {
        $this->classroom = $classroom;

        return $this;
    }

    /**
     * Get nOTE: This is not a mapped field of entity metadata, just a simple property.
     *
     * @return  File|null
     */ 
    public function getImageFile()
    {
        return $this->imageFile;
    }

    /**
     * Set nOTE: This is not a mapped field of entity metadata, just a simple property.
     *
     * @param  File|null  $imageFile  NOTE: This is not a mapped field of entity metadata, just a simple property.
     *
     * @return  self
     */ 
    public function setImageFile(?File $imageFile): Article
    {
        $this->imageFile = $imageFile;
        if ($this->imageFile instanceof UploadedFile)
        {
            $this->updatedAt = new \DateTime('now');
        }
        return $this;
    }

    /**
     * Get the value of imageName
     *
     * @return  string|null
     */ 
    public function getImageName()
    {
        return $this->imageName;
    }

    /**
     * Set the value of imageName
     *
     * @param  string|null  $imageName
     *
     * @return  self
     */ 
    public function setImageName($imageName)
    {
        $this->imageName = $imageName;

        return $this;
    }

    /**
     * Get the value of updatedAt
     *
     * @return  \DateTimeInterface|null
     */ 
    public function getUpdatedAt()
    {
        return $this->updatedAt;
    }

    /**
     * Set the value of updatedAt
     *
     * @param  \DateTimeInterface|null  $updatedAt
     *
     * @return  self
     */ 
    public function setUpdatedAt($updatedAt)
    {
        $this->updatedAt = $updatedAt;

        return $this;
    }
}

src/Entity/Classroom.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\ClassroomRepository")
 */
class Classroom
{
    const LEVEL = [
        0 => 'PS',
        1 => 'PS/MS',
        2 => 'MS',
        3 => 'MS/GS',
        4 => 'GS', 
        5 => 'GS/CP',
        7 => 'CP',
        8 => 'CP/CE1',
        9 => 'CE1',
        10 => 'CE1/CE2',
        11 => 'CE2',
        12 => 'CE2/CM1',
        13 => 'CM1',
        14 => 'CM1/CM2',
        15 => 'CM2'
    ];

    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\Column(type="integer")
     */
    private $year;

    /**
     * @ORM\Column(type="string", length=55, nullable=true)
     * @ORM\JoinColumn(nullable=false)
     * @var string|null
     */
    private $level;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\User", cascade={"persist"}, mappedBy="classroom", orphanRemoval=true)

     */
    private $users;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User", cascade={"persist"}, inversedBy="classrooms")
     */
    private $teacher;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Article", cascade={"remove"}, mappedBy="classroom")
     */
    private $articles;

    public function __construct()
    {
        $this->users = new ArrayCollection();
        $this->year = date('Y');
        $this->articles = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getYear(): ?int
    {
        return $this->year;
    }

    public function setYear(int $year): self
    {
        $this->year = $year;

        return $this;
    }

    public function getLevel()
    {
        return $this->level;
    }

    public function getLevelType(): string
    {
        return self::LEVEL[$this->level];
    }

    public function setLevel($level)
    {
        $this->level = $level;

        return $this;
    }

    /**
     * @return Collection|User[]
     */
    public function getUsers(): Collection
    {
        return $this->users;
    }

    public function addUser(User $user): self
    {
        if (!$this->users->contains($user)) {
            $this->users[] = $user;
            $user->setClassroom($this);
        }

        return $this;
    }

    public function removeUser(User $user): self
    {
        if ($this->users->contains($user)) {
            $this->users->removeElement($user);
            // set the owning side to null (unless already changed)
            if ($user->getClassroom() === $this) {
                $user->setClassroom(null);
            }
        }

        return $this;
    }

   public function  __toString(){
        return $this->name;
    }

   public function getTeacher(): ?User
   {
       return $this->teacher;
   }

   public function setTeacher(?User $teacher): self
   {
       $this->teacher = $teacher;

       return $this;
   }

   /**
    * @return Collection|Article[]
    */
   public function getArticles(): Collection
   {
       return $this->articles;
   }

   public function addArticle(Article $article): self
   {
       if (!$this->articles->contains($article)) {
           $this->articles[] = $article;
           $article->setClassroom($this);
       }

       return $this;
   }

   public function removeArticle(Article $article): self
   {
       if ($this->articles->contains($article)) {
           $this->articles->removeElement($article);
           // set the owning side to null (unless already changed)
           if ($article->getClassroom() === $this) {
               $article->setClassroom(null);
           }
       }

       return $this;
   }
}

templates/backoffice/family/index.html.twig
{% extends 'base.html.twig' %}

{% block title 'Tableau de bord | MonEcole' %}

{% block stylesheets %}<link rel="stylesheet" href="/css/backoffice.css">{% endblock %}

{% block body %}
    <div class="container-fluid">
        <div class="container pt-4">
            <div class="row">
                <div class="col-md-12">
                    <div class="card mb-3">
                        <div class="card-header" >
                            <div class="row">
                                <div class="col"> 
                                    <span class="h6 text-dark font-weight-bold m-0">Tableau de Bord</span>
                                </div>
                            </div>
                        </div>
                        <div class="card-body bg-dark align-items-center">
                            <div class="row d-flex mx-auto">
                                <div class="col-lg-3 text-left border-right">
                                    <p class="h4 font-weight-bold text-white">{{ user.firstname ~ " " ~ user.lastname }}</p>
                                    <p class="mt-5"><i class="fas fa-user-graduate fa-4x cream"></i></p>
                                    <p class="h5 font-weight-bold text-white">{{ user.classroom }}</p>
                                    <p class="h5 font-weight-bold text-white">{{ 'De ' ~ teacher.firstname ~ " " ~ teacher.lastname }}</p>
                                    <p class="h6 font-weight-bold text-white mt-5">Niveau :
                                        {% if user.classroom.level is not null %}
                                            {{ ' ' ~ user.classroom.levelType }}
                                        {% endif %}
                                    </p>
                                    <p class="h6 font-weight-bold text-white">{{ 'Année : ' ~ user.classroom.year }}</p>
                                </div>
                                <div class="col-lg-9 my-auto">
                                    {% if latestArticle %}
                                    <p class="h5"><a class="text-white text-decoration-none" href="{{ path('blog.article', {id: latestArticle.id}) }}">Dernier article du blog</a></p>
                                    <div class="row align-items-center">
                                        {% if latestArticle.imageName %}
                                        <div class="col-lg-5">
                                            <img class="img-fluid" src="{{ vich_uploader_asset(latestArticle, 'imageFile') }}" alt="Sample image">
                                        </div>
                                        <div class="col-lg-7 justify-content-between">
                                        {% else %}
                                        <div class="col-lg-12 justify-content-between">
                                        {% endif %}
                                            <div class="row my-2">
                                                <div class="col"> 
                                                    <span class="h6 font-weight-bold">{{ latestArticle.title}}</span>
                                                </div>
                                                <div class="col text-right"> 
                                                    <span class="h6 font-weight-bold">{{ latestArticle.categoryType}}</span>
                                                </div>
                                            </div>
                                            <p>{{ latestArticle.content|striptags|slice(0, 255)|raw }}...</p>
                                            <p class="font-weight-bold">{{ 'Publié le ' ~ latestArticle.createdAt | date('d/m/Y')}}</p> 
                                        </div>
                                    </div>
                                    <hr class="my-2">
                                    {% else %}
                                    <p class="cream text-center mb-3"><i class="fas fa-rss fa-5x"></i></p>
                                    <p class="cream text-center">Le blog de la classe ne contient pas encore d'article</p>
                                    <p class="text-white text-center">Revenez nous voir bientot !</p>
                                    {% endif %}
                                </div>
                            </div>
                            <div class="row d-flex mx-auto">
                                <div class="col-lg-3 border-right">
                                    <a class="buttonStyle btn btn-block font-weight-bold my-4" href="{{ path('liaison.show', {id: user.id}) }}" role="button">Carnet de liaison</a>
                                </div>
                                <div class="col-lg-9">
                                    <a class="buttonStyle btn btn-block font-weight-bold my-4" href="{{ path('blog.index', {id: user.classroom.id}) }}" role="button">Voir le blog de la classe</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/backoffice/family/show.html.twig
{% extends 'base.html.twig' %}

{% block title 'Carnet de liaison | MonEcole' %}

{% block stylesheets %}<link rel="stylesheet" href="/css/backoffice.css">{% endblock %}

{% block body %}
    <div class="container-fluid">
        <div class="container pt-4">
            <div class="row">
                <div class="col-md-12">
                    <div class="card mb-3">
                        <div class="card-header my-0" >
                            <div class="row">
                                <div class="col"> 
                                    <span class="h6 text-dark font-weight-bold">Carnet de liaison</span>
                                </div>
                                <div class="col text-right">
                                    <span class="mb-0 text-right"><a class="returnLink" href="{{ path('dashboard.index') }}"><i class="fas fa-long-arrow-alt-left fa-lg"></i></a></span>
                                </div>
                            </div>
                        </div>
                        <div class="card-body bg-dark">
                            {% if not messages %}
                                <div class="row cream text-center">
                                    <div class="col-md-12">
                                        <p class="mb-3">Le carnet de liaison est vide</p>
                                    </div>
                                </div>
                            {% endif %}
                            <div class="mb-3 ml-1">
                                <a class="mb-5 cream font-weight-bold" href="#formMessage" data-toggle="collapse">
                                    Nouveau message
                                    {# <i class="fas fa-caret-up"></i> #}
                                    <i class="fas fa-caret-down"></i>
                                </a>
                            </div>
                            <div id="formMessage" class="collapse">
                                {{ form_start(form) }}
                                    <div class="row cream">
                                        <div class="col-md-12">
                                            {{ form_row(form.subject) }}
                                        </div>
                                        <div class="col-md-12">
                                            {{ form_row(form.content) }}
                                            {# {{tinymce_init ()}} #}
                                            {# {{tinymce_init ({ ' use_callback_tinymce_init ' : true , ' theme ' : { ' simple ' : { ' menubar ' : false }}})}} #}
                                        </div>
                                    </div>
                                    {{ form_rest(form) }}
                                    <div class="row my-4 justify-content-center">
                                        <div class="col-md-12">
                                            <button class="buttonStyle btn btn-block font-weight-bold">Envoyer</a>
                                        </div>
                                    </div>
                                {{ form_end(form) }}
                            </div>
                            {% for message in messages %}
                                <div class="mx-1 py-3 row text-white border {% if message.transmitter == student %}bg-secondary{% else %}bg-dark{% endif %}">
                                    <div class="col-md-2 border-right">
                                        <div class="">le {{ message.createdAt | date('d/m/Y') }}</div>
                                    </div>
                                    <div class="col-md-10">
                                        <div class="h4">{{ message.subject }}</div>
                                        <div class="">{{ message.content }}</div>
                                        <div class="text-right">{{ message.transmitter }}</div>                                            
                                    </div>
                                </div>
                            {% endfor %}
                        </div>
                    </div>
                </div>
            </div>         
        </div>
    </div>
{% endblock %}