src/Entity/Message.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\MessageRepository")
 */
class Message
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="text")
     */
    private $content;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User", cascade={"persist", "remove"}, inversedBy="sendedMessages")
     * @ORM\JoinColumn(nullable=false, onDelete="CASCADE")
     */
    private $transmitter;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User", cascade={"persist", "remove"}, inversedBy="receivedMessages")
     * @ORM\JoinColumn(nullable=false, onDelete="CASCADE")
     */
    private $recipient;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $subject;

    /**
     * @ORM\Column(type="datetime")
     */
    private $created_at;

    /**
     * @ORM\Column(type="boolean", nullable=false, options={"default":0}))
     */
    private $open_transmitter = false;

    /**
     * @ORM\Column(type="boolean", nullable=false, options={"default":0}))
     */
    private $open_recipient = false;

    /**
     * @ORM\Column(type="boolean", nullable=false, options={"default":0}))
     */
    private $trash_transmitter = false;

    /**
     * @ORM\Column(type="boolean", nullable=false, options={"default":0}))
     */
    private $trash_recipient = false;

    /**
     * @ORM\Column(type="boolean", nullable=false, options={"default":0})
     */
    private $liaison = false;

    public function isOwner(User $user)
    {
        return ($this->getTransmitter() === $user || $this->getRecipient() === $user );
    }

    public function __construct()
    {
        $this->created_at = new \DateTime();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(string $content): self
    {
        $this->content = $content;

        return $this;
    }

    public function getTransmitter(): ?User
    {
        return $this->transmitter;
    }

    public function setTransmitter(?User $transmitter): self
    {
        $this->transmitter = $transmitter;

        return $this;
    }

    public function getRecipient(): ?User
    {
        return $this->recipient;
    }

    public function setRecipient(?User $recipient): self
    {
        $this->recipient = $recipient;

        return $this;
    }

    public function getSubject(): ?string
    {
        return $this->subject;
    }

    public function setSubject(?string $subject): self
    {
        $this->subject = $subject;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getOpenTransmitter(): ?bool
    {
        return $this->open_transmitter;
    }

    public function setOpenTransmitter(bool $open_transmitter): self
    {
        $this->open_transmitter = $open_transmitter;

        return $this;
    }

    public function getOpenRecipient(): ?bool
    {
        return $this->open_recipient;
    }

    public function setOpenRecipient(bool $open_recipient): self
    {
        $this->open_recipient = $open_recipient;

        return $this;
    }

    public function getTrashTransmitter(): ?bool
    {
        return $this->trash_transmitter;
    }

    public function setTrashTransmitter(bool $trash_transmitter): self
    {
        $this->trash_transmitter = $trash_transmitter;

        return $this;
    }

    public function getTrashRecipient(): ?bool
    {
        return $this->trash_recipient;
    }

    public function setTrashRecipient(bool $trash_recipient): self
    {
        $this->trash_recipient = $trash_recipient;

        return $this;
    }

    public function getLiaison(): ?bool
    {
        return $this->liaison;
    }

    public function setLiaison(bool $liaison): self
    {
        $this->liaison = $liaison;

        return $this;
    }

}

src/Form/MessageType.php
<?php

namespace App\Form;

use App\Entity\Message;
use App\Entity\User;
use App\Repository\UserRepository;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;

class MessageType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('recipient',EntityType::class, [
                'class' => User::class,
                'label' => 'Destinataire :', 
                'query_builder'=> function(UserRepository $repo) use ($options){
                    return $repo->findRecipientFor($options['user']);
                },
                // 'group_by' => 'roles'
                'group_by' => function (User $user){
                    if ($user->hasRole('ROLE_ADMIN'))
                    {
                        return 'Administrateur';
                    }
                    elseif ($user->hasRole('ROLE_TEACHER'))
                    {
                        return 'Instituteurs';
                    }else
                    {
                        return 'Élèves';
                    }
                }
            ])
            ->add('subject', TextType::class, ['label' => 'Objet :'])
            ->add('content', TextareaType::class, [
                'label' => 'Message :',
                'attr' => [
                    'class' => 'tinymce',
                    'rows' => 6
                ]
            ])
            // ->add('content', TextType::class, ['label' => 'Message :'])
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
$resolver->setRequired('user');
$resolver->setAllowedTypes('user', User::class);


        $resolver->setDefaults([
            'data_class' => Message::class
        ]);
    }
}

src/Controller/MessageController.php
<?php

namespace App\Controller;

use App\Entity\Message;
use App\Form\MessageType;
use App\Form\MessageReplyType;
use App\Repository\UserRepository;
use App\Repository\MessageRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Security\Core\Exception\AccessDeniedException;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;

class MessageController extends AbstractController
{
    /**
     *
     * @var MessageRepository
     */
    private $repository;

    public function __construct(UserRepository $userRepository, MessageRepository $repository, EntityManagerInterface $entityManager)
    {
        $this->userRepository = $userRepository;
        $this->repository = $repository;
        $this->entityManager = $entityManager;
    }

    /**
     * @Route("/message", name="admin.message.index")
     * @return Response
     */
    public function index()
    {
        $user = $this->getUser();
        $receivedMessages = $this->repository->findBy(['recipient' => $user, 'trash_recipient' => false], ['id' => 'desc']);
        $sendedMessages = $this->repository->findBy(['transmitter' => $user, 'trash_transmitter' => false], ['id' => 'desc']);

        return $this->render('backoffice/message/index.html.twig', [
            'receivedMessages' => $receivedMessages,
            'sendedMessages' => $sendedMessages,
        ]);
    }

    /**
     * @Route("/messages/check", name="message.check")
     * @return Response
     */
    public function check()
    {
        $user = $this->getUser();
        $notOpenMessages = $this->repository->findBy(['recipient' => $user, 'open_recipient' => false], ['id' => 'desc']);
        $messagesCount = count($notOpenMessages);

        return $this->json(['count' => $messagesCount]);
    }

    /**
     * @Route("/message/show/{id}", name="admin.message.show")
     * @param Message $message
     * @return Response
     */
    public function show(Message $message)
    {
        // TODO attention on ne doit pas pouvoir voir le message de quelqu'un d'autre

        if($message->isOwner($this->getUser()))
        {
            if($message->getRecipient() === $this->getUser() && $message->getOpenRecipient() === false)
            {
                $message->setOpenRecipient(true);
                $this->entityManager->flush();
            }

            if($message->getRecipient() === $this->getUser())
            {
                return $this->render('backoffice/message/received.html.twig', compact('message'));
            }
            else
            {
                return $this->render('backoffice/message/sended.html.twig', compact('message'));   
            }
        }
        else
        {
            throw new AccessDeniedException();
        }

    }

    /**
     * @Route("/message/create", name="admin.message.new")
     * @IsGranted("ROLE_USER")
     */
    public function new(Request $request)
    {
        $message = new Message();
        $form = $this->createForm(MessageType::class, $message, ['user'=> $this->getUser()]);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid())
        {
            $message->setTransmitter($this->getUser());
            $message->setOpenTransmitter(true);
            $message->setLiaison(false);
            $this->entityManager->persist($message);
            $this->entityManager->flush();
            $this->addFlash('success', 'Le message a été envoyé avec succès');
            return $this->redirectToRoute('admin.message.index');
        }

        return $this->render('backoffice/message/new.html.twig',[
            'message' => $message,
            'form' => $form->createView()
        ]);
    }

    /**
     * @Route("/message/{id}/reply", name="admin.message.reply", methods="GET|POST")
     * @param Message $message
     * @param Request $request
     * @return Response
     */
    public function reply(Message $message, Request $request)
    {
        $reply = new Message();
        $form = $this->createForm(MessageReplyType::class, $reply);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid())
        {
            $reply->setTransmitter($this->getUser());
            $reply->setRecipient($message->getTransmitter());
            $reply->setSubject('RE: ' . $message->getSubject());
            $reply->setOpenTransmitter(true);
            $reply->setLiaison(false);
            $this->entityManager->persist($reply);
            $this->entityManager->flush();
            $this->addFlash('success', 'Le message a été envoyé avec succès');
            return $this->redirectToRoute('admin.message.index');
        }

        return $this->render('backoffice/message/reply.html.twig',[
            'message' => $message,
            'form' => $form->createView()
        ]);
    }

    /**
     * @Route("/message/{id}", name="admin.message.delete", methods="DELETE")
     * @param Message $message
     * @return Response
     */
    public function delete(Message $message, Request $request)
    {
        if ($this->isCsrfTokenValid('delete' . $message->getId(), $request->get('_token')))
        {
            if($message->getTransmitter() === $this->getUser() && $message->getTrashTransmitter() === false)
            {
                $message->setTrashTransmitter(true);
                $this->entityManager->flush();
                $this->addFlash('success', 'Le message a été supprimé avec succès');
            }

            if($message->getRecipient() === $this->getUser() && $message->getTrashRecipient() === false)
            {
                $message->setTrashRecipient(true);
                $this->entityManager->flush();
                $this->addFlash('success', 'Le message a été supprimé avec succès');
            }

            if ($message->getTrashTransmitter() === true && $message->getTrashRecipient() === true && $message->getLiaison() === false)
            {
                $this->entityManager->remove($message);
                $this->entityManager->flush();
            }
        }

        return $this->redirectToRoute('admin.message.index');
    }
}

templates/backoffice/message/index.html.twig
{% extends 'base.html.twig' %}

{% block title 'Messagerie | MonEcole' %}

{% block stylesheets %}<link rel="stylesheet" href="/css/backoffice.css">{% endblock %}

{% block body %}
    <div class="container-fluid">
        <div class="container pt-4">
            <div class="row mb-2">
                <div class="col-md-12">
                    <h1 class="h3 mb-2 text-gray-800">Messages</h1>
                </div>
                <div class="d-md-flex col-md-12 justify-content-between">
                    <div class="">
                        <span class="small font-italic"><a class="text-dark" href="{{ path('dashboard.index') }}"><i class="fas fa-home mr-1"></i>Tableau de bord</a></span>
                        <span class="small font-italic">/</span>
                        <span class="small font-italic">Messages</span>
                    </div>
                    <div class="">
                        <span class="h3 mb-0 text-right"><a class="returnLink" href="{{ path('dashboard.index') }}"><i class="fas fa-long-arrow-alt-left fa-lg"></i></a></span>
                    </div>
                </div>
            </div>

            <div class="row">
                <div class="col-md-12">
                    <div class="card mb-3">
                        <div class="card-header my-0" >
                            <div class="row">
                                <div class="col">
                                    <ul class="nav nav-pills" id="pills-tab" role="tablist">
                                        <li class="nav-item">
                                            <a class="nav-link active text-dark font-weight-bold py-0" id="pills-received-tab" data-toggle="pill" href="#pills-received" role="tab" aria-controls="pills-received" aria-selected="true"><i class="fas fa-inbox mr-2"></i>Recus</a>
                                        </li>
                                        <li class="nav-item">
                                            <a class="nav-link text-dark font-weight-bold py-0" id="pills-sended-tab" data-toggle="pill" href="#pills-sended" role="tab" aria-controls="pills-sended" aria-selected="false"><i class="fas fa-paper-plane mr-2"></i>Envoyés</a>
                                        </li>
                                    </ul>
                                </div>
                                <div class="col text-right"> 
                                    <a class="font-weight-bold create" href="{{ path('admin.message.new') }}" role="button"><i class="fas fa-plus fa-xl"></i></a>
                                </div>
                            </div>
                        </div>
                        <div class="tab-content" id="pills-tabContent">
                            <div class="tab-pane fade show active" id="pills-received" role="tabpanel" aria-labelledby="pills-received-tab">
                                <div class="card-body bg-dark">
                                    {% if not receivedMessages %}
                                        <div class="row cream text-center">
                                            <div class="col-md-12">
                                                <p class="m-0">Vous n'avez pas de message reçu</p>
                                            </div>
                                        </div>
                                    {% else %}
                                    <table class="table table-hover table-dark text-white">
                                        <thead>
                                            <tr>
                                                <th class="cream" style="width: 5%"><i class="fas fa-envelope"></i></th>
                                                <th class="cream" style="width: 15%">Expediteur</th>
                                                <th class="cream" style="width: 15%">Date</th>
                                                <th class="cream" style="width: 20%">Objet</th>
                                                <th class="cream" style="width: 45%">Apercu</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                        {% for receivedMessage in receivedMessages %}
                                            <tr onclick="document.location='{{ path('admin.message.show', {id: receivedMessage.id}) }}'">
                                                <td style="width: 5%">
                                                    {% if receivedMessage.openRecipient == true %}
                                                        <i class="fas fa-envelope-open"></i>
                                                    {% else %}
                                                        <i class="fas fa-envelope cream"></i>
                                                    {% endif %}
                                                </td>
                                                <td style="width: 15%">{{ receivedMessage.transmitter.firstname ~ ' ' ~ receivedMessage.transmitter.lastname }}</td>
                                                <td style="width: 15%">{{ receivedMessage.createdAt | date('d/m/Y') }}</td>
                                                <td style="width: 20%">{{ receivedMessage.subject|striptags|slice(0, 25)|raw }}</td>
                                                <td style="width: 45%">{{ receivedMessage.content|striptags|slice(0, 50)|raw }}...</td>
                                            </tr>
                                        {% endfor %}
                                        </tbody>
                                    </table>
                                    {% endif %}
                                    <div class="row mt-4 justify-content-center">
                                        <div class="col-md-12">
                                            <a class="buttonStyle btn btn-block font-weight-bold" href="{{ path('admin.message.new') }}" role="button">Nouveau message</a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="tab-pane fade show" id="pills-sended" role="tabpanel" aria-labelledby="pills-sended-tab">
                                <div class="card-body bg-dark">
                                    {% if not sendedMessages %}
                                        <div class="row cream text-center">
                                            <div class="col-md-12">
                                                <p class="m-0">Vous n'avez pas de message envoyés</p>
                                            </div>
                                        </div>
                                    {% else %}
                                    <table class="table table-hover table-dark text-white">
                                        <thead>
                                            <tr>
                                                <th class="cream" style="width: 5%"><i class="fas fa-paper-plane"></i></th>
                                                <th class="cream" style="width: 15%">Destinataire</th>
                                                <th class="cream" style="width: 15%">Date</th>
                                                <th class="cream" style="width: 20%">Objet</th>
                                                <th class="cream" style="width: 45%">Apercu</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                        {% for sendedMessage in sendedMessages %}
                                            <tr onclick="document.location='{{ path('admin.message.show', {id: sendedMessage.id}) }}'">
                                                <td style="width: 5%"><i class="fas fa-paper-plane"></i></td>
                                                <td style="width: 15%">{{ sendedMessage.recipient.firstname ~ ' ' ~ sendedMessage.recipient.lastname}}</td>
                                                <td style="width: 15%">{{ sendedMessage.createdAt | date('d/m/Y') }}</td>
                                                <td style="width: 20%">{{ sendedMessage.subject|striptags|slice(0, 25)|raw }}</td>
                                                <td style="width: 45%">{{ sendedMessage.content|striptags|slice(0, 50)|raw }}...</td>
                                            </tr>
                                        {% endfor %}
                                        </tbody>
                                    </table>
                                    {% endif %}
                                    <div class="row mt-4 justify-content-center">
                                        <div class="col-md-12">
                                            <a class="buttonStyle btn btn-block font-weight-bold" href="{{ path('admin.message.new') }}" role="button">Nouveau message</a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>         
        </div>
    </div>
{% endblock %}

templates/backoffice/message/received.html.twig
{% extends 'base.html.twig' %}

{% block title 'Message ? | MonEcole' %}

{% block stylesheets %}<link rel="stylesheet" href="/css/backoffice.css">{% endblock %}

{% block body %}
    <div class="container-fluid">
        <div class="container pt-4">
            <div class="row mb-2">
                <div class="col-md-12">
                    <h1 class="h3 mb-2 text-gray-800">Messages</h1>
                </div>
                <div class="d-md-flex col-md-12 justify-content-between">
                    <div class="">
                        <span class="small font-italic"><a class="text-dark" href="{{ path('dashboard.index') }}"><i class="fas fa-home mr-1"></i>Tableau de bord</a></span>
                        <span class="small font-italic">/</span>
                        <span class="small font-italic"><a class="text-dark" href="{{ path('admin.message.index') }}">Messages</a></span>
                        <span class="small font-italic">/</span>
                        <span class="small font-italic">Reçu</span>
                    </div>
                    <div class="">
                        <span class="h3 mb-0 text-right"><a class="returnLink" href="{{ path('admin.message.index') }}"><i class="fas fa-long-arrow-alt-left fa-lg"></i></a></span>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12">
                    <div class="card mb-3">
                        <div class="card-header my-0" >
                            <div class="row">
                                <div class="col"> 
                                    <span class="h6 text-dark font-weight-bold">Reçu</span>
                                </div>
                                <div class="col text-right"> 
                                    <form method="post" action="{{ path('admin.message.delete', {id: message.id}) }}" style="display: inline-block;" onsubmit="return confirm('Êtes vous sur de vouloir supprimer ce message ?')">
                                        <input type="hidden" name="_method" value="DELETE">
                                        <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ message.id) }}">
                                        <button class="deleteBtn font-weight-bold"><i class="fas fa-trash-alt"></i></button>
                                    </form>
                                </div>
                            </div>
                        </div>
                        <div class="card-body bg-dark">
                            <div class="row my-2">
                                <div class="col-md-6">
                                    <span class="cream font-weight-bold">De : </span>
                                    <span class="text-white">{{ message.transmitter.firstname ~ ' ' ~ message.transmitter.lastname }}</span>
                                </div>
                                <div class="col-md-6 text-right">
                                    <span class="cream font-weight-bold">le :</span>
                                    <span class="text-white">{{ message.createdAt | date('d/m/Y') }}</span>
                                </div>
                            </div>
                            <div class="row mt-4">
                                <div class="col-md-12">
                                    <span class="cream font-weight-bold">Sujet :</span>
                                    <span class="text-white">{{ message.subject }}</span>
                                </div>
                            </div>
                            <div class="row my-4">
                                <div class="col-md-12 text-white">
                                    {{ message.content }}
                                </div>
                            </div>
                            <div class="row mt-5 justify-content-center">
                                <div class="col-md-6">
                                    <a class="buttonStyle btn btn-block font-weight-bold" href="{{ path('admin.message.reply', {id: message.id}) }}" role="button">Répondre</a>
                                </div>
                                <div class="col-md-6">
                                    <form method="post" action="{{ path('admin.message.delete', {id: message.id}) }}" onsubmit="return confirm('Êtes vous sur de vouloir supprimer ce message ?')">
                                        <input type="hidden" name="_method" value="DELETE">
                                        <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ message.id) }}">
                                        <button class="buttonStyle btn btn-block font-weight-bold" style="width: 100%;" >Supprimer</i></button>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>         
        </div>
    </div>
{% endblock %}

templates/backoffice/message/reply.html.twig
{% extends 'base.html.twig' %}

{% block title 'Nouveau message | MonEcole' %}

{% block stylesheets %}<link rel="stylesheet" href="/css/backoffice.css">{% endblock %}

{% block body %}
    <div class="container-fluid">
        <div class="container pt-4">
            <div class="row mb-2">
                <div class="col-md-12">
                    <h1 class="h3 mb-2 text-gray-800">Messages</h1>
                </div>
                <div class="d-md-flex col-md-12 justify-content-between">
                    <div class="">
                        <span class="small font-italic"><a class="text-dark" href="{{ path('dashboard.index') }}"><i class="fas fa-home mr-1"></i>Tableau de bord</a></span>
                        <span class="small font-italic">/</span>
                        <span class="small font-italic"><a class="text-dark" href="{{ path('admin.message.index') }}">Messages</a></span>
                        <span class="small font-italic">/</span>
                        <span class="small font-italic">Répondre au message</span>
                    </div>
                    <div class="">
                        <span class="h3 mb-0 text-right"><a class="returnLink" href="{{ path('admin.message.index') }}"><i class="fas fa-long-arrow-alt-left fa-lg"></i></a></span>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12">
                    <div class="card mb-3">
                        <div class="card-header my-0" >
                            <div class="row">
                                <div class="col"> 
                                    <span class="h6 text-dark font-weight-bold">Répondre au message</span>
                                </div>
                            </div>
                        </div>
                        <div class="card-body bg-dark">
                            <div class="row my-2">
                                <div class="col-md-6">
                                    <span class="cream font-weight-bold">De : </span>
                                    <span class="text-white">{{ message.transmitter ~ ', le ' ~ message.createdAt | date('d/m/Y')}}</span>
                                </div>
                                <div class="col-md-6">
                                    <span class="cream font-weight-bold">Sujet :</span>
                                    <span class="text-white">{{ message.subject }}</span>
                                </div>
                            </div>
                            <div class="row my-4">
                                <div class="col-md-12 cream font-weight-bold">Message reçu :</div>
                                <div class="mt-2 col-md-12 text-white">{{ message.content }}</div>
                            </div>
                            {{ form_start(form) }}
                                <div class="row">                           
                                    <div class="col-md-12 cream">
                                        {{ form_row(form.content) }}
                                        {# {{tinymce_init ()}} #}
                                        {# {{tinymce_init ({ ' use_callback_tinymce_init ' : true , ' theme ' : { ' simple ' : { ' menubar ' : false }}})}} #}
                                    </div>
                                </div>
                                {{ form_rest(form) }}
                                <div class="row mt-4 justify-content-center">
                                    <div class="col-md-12">
                                        <button class="buttonStyle btn btn-block font-weight-bold">Envoyer</a>
                                    </div>
                                </div>
                            {{ form_end(form) }}
                        </div>
                    </div>
                </div>
            </div>         
        </div>
    </div>
{% endblock %}